### ISSUE TITLE
Big break in new firefox

### ISSUE THREAD

**Issue by majkimajki** [OwlCarousel2/OwlCarousel2#2144] opened 2017-11-30 11:08 UTC
Any one also encountered a problem with firefox making a big gap under the owl carousel?
Only happens in the new FF.

**Comment by artus70** [comment] 2017-12-08 10:37
Yeah, it seems to be kind of rounding error. If you increase the width of div.owl-stage by 1px in developer tools, it instantly works. Otherwise the last li element in the list doesn't fit into the div and thus is displayed in a second row.

![grafik](https://user-images.githubusercontent.com/367315/33762110-a9ad0686-dc0b-11e7-93ec-70a55cba161e.png)

**Comment by majkimajki** [comment] 2017-12-08 13:14
Hmm, seems to be fine in the newest update on FF.

**Comment by artus70** [comment] 2017-12-08 13:34
@majkimajki I can't confirm that. I'm on FF 58.0b9 (64-Bit), problem remains.

**Comment by pascalporedda** [comment] 2018-02-12 11:14
@majkimajki and @artus70 Is this problem still existing?

**Comment by artus70** [comment] 2018-02-16 12:35
@pascalporedda The problem is gone here, but I don't know whether our service provider did change anything on it inbetween.

**Comment by any-one** [comment] 2018-02-16 14:12
I have that problem too with the last element showing up in a second row - only on Firefox (58.0.2, 64-Bit) - Chrome and IE11 work fine.

The strange this is that it only happens on initial load of the page (owl-stage width shows is 3307px ), and not always. after a refresh it's OK again or when I resize the window horizontally making the layout shrink or expand (owl-stage width changes to 3348px) .

**Comment by pascalporedda** [comment] 2018-02-17 08:57
@artus70 Alright, as this seems to be no problem in the latest version of firefox I will close this issue as I was not able to replicate it in any way.

**Closed by pascalporedda** 2018-02-17 08:57 UTC
Labels: question
