### ISSUE TITLE
autoplayHoverPause does not re-start after timeout

### ISSUE THREAD

**Issue by CristyTarantino** [OwlCarousel2/OwlCarousel2#1695] opened 2017-01-13 14:29 UTC
Hi,

I have tried those setting:

```  {
    items: 1,
    loop: true,
    animateOut: 'fadeOut',
    animateIn: 'fadeIn',
    autoplay: true,
    autoplaySpeed: 1000,
    autoPlayTimeout: 1000,
    autoplayHoverPause: true
  }
```

but once I hover out or after 1000ms the autoplay doesn't restart.

Is it suppose to behave like this?

Thank you.

**Comment by Saajan** [comment] 2017-01-15 19:23
Try giving higher value than 1000. it worked for me.

**Comment by muhamed87** [comment] 2017-01-17 08:59
@Saajan Which version do you use, because I have the same issue as @CristyTarantino in the version 2.2.0 and it is working perfectly in a previous version (beta 2.0.0)

Same issue here also if you go to another tab in the browser and go back you will find the carousel stopped
https://github.com/OwlCarousel2/OwlCarousel2/issues/1674

**Comment by CristyTarantino** [comment] 2017-01-17 15:56
I use version 2.2.0 and even with a higher value than 1000 I still have the same issue.

**Comment by sanPuerquitoProgramador** [comment] 2017-01-19 02:47
May be you can try with the Jason Engage version: https://github.com/jason-engage/awesome-media-carousel it's the same owl carousel with a little modification.

I use this version for create a carousel without stop (like a headline news) and found that, in this specific type, the carousel doesn't stop when the tab lose focus.

I'm still working on more tests.


 ```
/*Headlines News*/
   if($(".headlines-top").length){
        $(".headlines-top").owlCarousel({
            slideTransition: 'linear',
            autoplay:true,
            autoplayTimeout: 0,
            autoplaySpeed: 10000,
            loop:true,
            items:1,
            dots:false
        });
    }
```

**Comment by damirkoch** [comment] 2017-02-13 16:30
(Sorry about the canned reply.)

You have not added a link to a working live example.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Closed by damirkoch** 2017-02-13 16:30 UTC

**Comment by aristidesfl** [comment] 2017-02-13 17:10
I can reproduce this on 2.2.0.
