### ISSUE TITLE
bug: sliding an item with thick border

### ISSUE THREAD

**Issue by soundsbeard** [OwlCarousel2/OwlCarousel2#1641] opened 2016-11-22 22:39 UTC
https://jsfiddle.net/7uzou3L4/2/

using jquery 2.2.4
carousel is not looped
the first item is wrapped with a ref to youtube (or whereever)

so grab the first item from the center of item and drag the cursor to the next item and release.
carousel returns to the start point, nothing happens, its ok.
grab it from the center and release while cursor is still under the blue area of the first item.
everything is ok, still predictable.
but if you grab the wrapped item from the center and release it while the cursor is under the borders/margin of the item - it performes a click,
so I guess it is bug.

**Comment by CracyCrazz** [comment] 2016-11-28 14:58
I am sorry, but I actually cannot reproduce this bug on your fiddle. Could you provide me with a "working" fiddle?

**Comment by soundsbeard** [comment] 2016-11-28 15:08
hi, I have increased margin of the item, so I hope you will see what I mean.
https://jsfiddle.net/soundsbeard/p868kajn/4/

**Comment by pascalporedda** [comment] 2017-02-13 15:23
(Sorry about the canned reply.)

You have not added a link to a working live example. The fiddle you provided just displays all items below each other.

Please add a link to a page where I can verify this error. You can use a service like [jsfiddle](http://jsfiddle.net/), [plnkr](https://plnkr.co/), [jsbin](http://jsbin.com/) or [codepen](http://codepen.io/).

And make sure you're using the latest Owl Version! I will close this issue for now, once you provided a working example you can reopen it.

**Closed by pascalporedda** 2017-02-13 15:23 UTC
