### ISSUE TITLE
Does not work in responsive mode

### ISSUE THREAD

**Issue by coda-apps** [OwlCarousel2/OwlCarousel2#1711] opened 2017-01-25 19:38 UTC
I have an installation of owl on a site - works perfectly in desktop mode, but in mobile mode, the slides seem to disappear completely.

My site is at: www.ypt.co.il (the 4 blocks below the large main slider - check it first in desktop mode).

This is the plugin code:
```

    $('.owl-carousel').owlCarousel({
        loop:true,
        margin:27,
        nav:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:3
            },
            992:{
                items:4
            }
        }
    });

```
Any input appreciated!

**Comment by CracyCrazz** [comment] 2017-02-13 10:28
It works out perfectly for me, can't reproduce this issue. Tested with latest chrome browser.

If you still experience this issue please go further into detail. Until then I will close this issue.

**Closed by CracyCrazz** 2017-02-13 10:28 UTC

**Comment by coda-apps** [comment] 2017-02-13 10:37
Thanks.
Turned out i did not have the res() function running in all correct places.
As soon as i added it  as follows, it worked:

`
$(function () {
  res();
});
`
