### ISSUE TITLE
Autoplay timer not reset when using nav dots

### ISSUE THREAD

**Issue by wing5wong** [OwlCarousel2/OwlCarousel2#993] opened 2015-08-19 22:50 UTC
When interacting with the nav dots, the timer is not reset on each click.
This results in slides changing instantly to the next slide if clicked before timer ticks, whereas i would expect the next transition to happen after another timeout period
e.g. with 3second autoplay,
0s - initial slide
2.5s - click nav dot, slide changes
3s - slide transitions to next slide slide has been displayed only .5s)
5.5s - The expected next slide change time ( slide is displayed for 3 seconds total)

**Comment by greg5green** [comment] 2015-08-20 01:44
Thanks for the report. This is how I would expect things to work as well.

**Comment by greg5green** [comment] 2015-08-20 01:45
[Simple test case](http://codepen.io/anon/pen/rVENKy)

**Comment by tdecaluwe** [comment] 2016-01-28 17:11
Duplicate of #440.

**Comment by daviddeutsch** [comment] 2017-07-25 10:07
See #1942

**Closed by daviddeutsch** 2017-07-25 10:07 UTC
Labels: approved for development, bug, help wanted

**Comment by 1ucay** [comment] 2017-12-30 14:11
For me not working. Im using beta 2.3.0

    $('.main-slider__slider').owlCarousel({
        autoplay: true,
        autoplayTimeout: 2000,
        loop: true,
        center: true,
        items: 1,
        mouseDrag: false,
        animateIn: 'fadeIn',
        animateOut: 'fadeOut',
        lazyLoad: true
    });

**Comment by aaburlaka** [comment] 2018-11-04 04:19
Please, return to this issue! Problem still here. Owl Carousel v2.2.1 hasn't this bug, but since v2.3.1 it began.

**Comment by wzol** [comment] 2018-11-04 06:04
I used an ugly workaround for this: https://github.com/OwlCarousel2/OwlCarousel2/issues/2452#issuecomment-430977063
