### ISSUE TITLE
owl-nav disabled 

### ISSUE THREAD

**Issue by Messa1** [OwlCarousel2/OwlCarousel2#1809] opened 2017-03-24 10:17 UTC
Hey. 

I have a problem with the owl-nav. 
I set it true but at the HTML output it adds the class "disabled".

Here my code i use the latest version, i downloaded it today.

```
<script type='text/javascript'>

jQuery(document).ready(function($) {
	 $('.owl-carousel').owlCarousel({
		nav: true,
		items: 1,
		loop: true,
		center: true,
		margin: 0,
		lazyLoad:true,
		dots: false
	});
 })

</script>"

```

**Comment by AndiKeiser** [comment] 2017-03-24 13:46
Is there more than one item in the carousel ?

**Comment by Messa1** [comment] 2017-03-24 13:47
No, at the moment only one for developing. I add a second and see whats happen.

**Comment by Messa1** [comment] 2017-03-24 13:48
Oky tested it, can be closed. Works now with second element.

**Comment by enjdusan** [comment] 2017-06-16 11:53
I have a same issue (v2.2.1)

```
$('.owl-carousel').owlCarousel({
    center: true,
    items: 3,
    loop: true,
    margin: 10,
    nav: true
});
```
I have centered gallery with three (now) images and .owl-nav gets class disabled. Same for .owl-dots.

**Comment by coder618** [comment] 2017-07-04 08:03
I have same issue, but i am using multiple slider in same page.

main.js
```
$('#owl-two').owlCarousel({
        loop:true,
        margin:30,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:2
            },
            1000:{
                items:3
            }
        }
    });

    $('#owl-one').owlCarousel({
        loop:true,
        navText:['<button type="button" class="btn slider-left-btn"> </button>','<button type="button" class="btn slider-right-btn"> </button>'],
        dots:true,
        margin:100,
        nav:true,
        responsive:{
            0:{
                items:1
            },
            600:{
                items:1
            },
            1000:{
                items:1
            }
        }
    });
```
html markup
```
<div id="owl-one" class="owl-carousel owl-theme">
</div>
<div id="owl-two" class="owl-carousel owl-theme">
</div>
```

**Comment by emnoise** [comment] 2017-07-18 12:13
The dots are only shown when the number of existing elements exceeds the number of visible elements.

**Comment by lear2000** [comment] 2017-07-18 16:27
Same Here.. 
hacked my js to show anyway.

`    $('#featuredproducts .owl-nav').removeClass('disabled');

    $('#featuredproducts .owl-nav').click(function(event) {
      $(this).removeClass('disabled');
    });`

**Comment by shafikulislam** [comment] 2017-08-02 14:18
Go To owl.carousel.min.js or owl.carousel.js file whatever you linked. Find and Replace 'disabled' with 'anyClass'. Done !!!

**Comment by foysal-ahamed** [comment] 2017-08-13 16:47
How many item you had? if there is one elements and your item is 1 so that means there is owl nav disabled by default. make your carousel 3 and then item: 1. nav will show

**Comment by coder618** [comment] 2017-08-14 12:27
@foysal-ahamed , @emnoise , @shafikulislam  Yes you people are correct, its happened because carousel did not have enough item's.

**Comment by applesapples1** [comment] 2017-08-15 20:46
I have tried using one item, 3 items, 2 items, but no matter what the owl-nav and owl-dots don't appear. It's not css — there isn't any markup for these elements. Could you please help me?

I'm using v 2.1.6. 

Here's my js:
    $('.owl-carousel').owlCarousel({
      navSpeed: 350,
      animateIn: 'fadeIn',
      animateOut: 'fadeOut',
      items: 1,
      lazyLoad: true,
      nav: true,
      dots: true,
      navText: [
        "<span class='icon icon-arrows-left'></span>",
        "<span class='icon icon-arrows-right'></span>"
      ],
    });

**Comment by rlambertsen** [comment] 2017-10-25 14:25
I am getting the same issue. 
``` $('.product-lines').owlCarousel({
                items: 4,
                loop: true,
                margin: 15,
                autoplay: true,
                autoplayTimeout: 5000,
                autoplayHoverPause: true,
                nav: true,
                responsive: {
                    0: {
                        items: 1
                    },
                    479: {
                        items: 1
                    },
                    768: {
                        items: 2
                    },
                    979: {
                        items: 3
                    },
                    1200: {
                        items: 4
                    }
                }
            });```
Not sure why but this should be fixed asap as the navigation is an important UI/UX feature of any slider or carousel.  I will create a pull request if that hasn't already been done.

**Comment by coder618** [comment] 2017-10-26 01:38
if your view-able items is less than total items than navigation will disable automatically. in other word you must have enough items to view Navigation which offer from Owl-carousel @rlambertsen

**Comment by ivan-frolov-webdev** [comment] 2017-11-24 16:47
I have a simple trick:

```
$('.owl-carousel').find('.owl-nav').removeClass('disabled');
$('.owl-carousel').on('changed.owl.carousel', function(event) {
	$(this).find('.owl-nav').removeClass('disabled');
});
```

**Comment by elhaw** [comment] 2018-03-12 14:24
just display **_owl-nav_** as block and give it important
`.owl-nav {
    display: block !important;
}`

**Comment by pascalporedda** [comment] 2018-03-16 11:17
I will close this issue, as there are many proposed solutions.

**Closed by pascalporedda** 2018-03-16 11:17 UTC

**Comment by JDeuce** [comment] 2018-04-06 18:31
None of the proposed solutions are really that usable though, the project should offer an extra setting for whether or not to hide the dots when there are less items.

**Comment by otherJeannie** [comment] 2018-05-18 16:42
@pascalporedda @JDeuce especially in the case when there are the same number of items as are viewable but `loop` is set to `true` ... this is a bug.

**Comment by mostafa-saqr** [comment] 2018-05-24 09:56
hay the problem is if you make a  items:3 for ex to view 3 element/slide and you put 3 items only so the nav will be disabled try to put more than 3 element so nav will work because now you have more than 3 element and you configure to present 3 items only/ slide so you should use nav to see more elements. make sense

**Comment by kubiqsk** [comment] 2018-06-29 18:22
It's bug, I'll explain:
imagine this:
{
	nav: 1,
	loop: 1,
	items: 6,
	autoWidth: 1,
}
but the 6th element is visible only partly because of autoWidth and there is also enabled loop, but there is no navigation!
That's really bad, I can fix it by customizing owl core js, but that's bad practise

**Comment by jevonthomas** [comment] 2018-08-10 14:06
@ivan-frolov-webdev your trick works. Thanks!!!!!!!

**Comment by sabbirshawon** [comment] 2019-02-24 12:44
I have facing same issues: 

      jQuery(document).ready(function(){
        jQuery('.owl-carousel').owlCarousel({

        margin: 10,

        nav: true,

        navText:["<i class='fa fa-arrow-left'></i>","<i class='fa fa-arrow-right'></i>"],

        responsive: {

            0: {

                items: 1

            },

            600: {

                items: 3

            },

            1000: {

                items: 3

            }
        }
    });
   });`

**Comment by RahilNIT** [comment] 2019-03-05 08:04
I Have Same Problem and Its bcs there is 4 carousel in One Page , Otherwise this worked: 
> nav: true,

**Comment by damien-roche** [comment] 2019-03-14 09:22
Same issue when enabling nav in using `responsive` options. This plugin is causing so many headaches.

**Comment by ghost** [comment] 2019-04-07 10:04
I happens when ````items:```` is equal to current slide blocks count. For example you have 4 image in slider and ````items```` set to 4. It will add ````disabled:```` manually. Adding images to slider more than count of ````items:```` will fix problem.

**Comment by deepstha** [comment] 2019-05-28 16:35
Great, Thankx

**Comment by brandondeweese** [comment] 2019-06-25 01:55
> I happens when `items:` is equal to current slide blocks count. For example you have 4 image in slider and `items` set to 4. It will add `disabled:` manually. Adding images to slider more than count of `items:` will fix problem.

Really? Because I can only get the nave to show if I have 4 or more images in the slider, regardless of the number of items I have.

**Comment by ghost** [comment] 2019-06-25 09:39
> > I happens when `items:` is equal to current slide blocks count. For example you have 4 image in slider and `items` set to 4. It will add `disabled:` manually. Adding images to slider more than count of `items:` will fix problem.
> 
> Really? Because I can only get the nave to show if I have 4 or more images in the slider, regardless of the number of items I have.

I think you set ````items```` count to 4. That's why this happens.

**Comment by jesorstaff** [comment] 2019-08-28 06:32
RU: У меня тоже стоял nav: true и в разметке было <div class="owl-nav disabled">
У вас должно быть больше элементов, чем на вашем экране (тогда какой смысл от навигации если у вас всего 1-2 элемента)

ENG: I also had nav: true and the markup was <div class = "owl-nav disabled">
You should have more elements than on your screen (then what's the point of navigating if you only have 1-2 elements)

**Comment by JonhCanedo** [comment] 2019-08-28 14:25
**It works for me!
goodlock!**

_<style>
    .owl-nav{
        display: none;
    }
</style>_

**Comment by naigueldev** [comment] 2019-08-30 12:12
In version 2.3.4 there is no such bug. Update plugin file versions.

**Comment by naigueldev** [comment] 2019-08-30 13:13
In older versions, the param is navigation: true for activate nav ...

`var owl = $('#carousel');
            owl.owlCarousel({
		autoPlay: true,
		navigation: true,
		slideSpeed: 600,
		items : 4,
		itemsDesktop : [1239,3],
		itemsTablet : [991,2],
		itemsMobile : [767,1]
	});`

**Comment by uttamkrchowdhury** [comment] 2019-10-14 05:38
If I use in react js then what to write to disable dots or navigation in responsive viewport?

**Comment by gurpreetsingh04** [comment] 2020-01-07 10:30
You need to include "owl.navigation.js" also then only navigation and dots will show.

**Comment by rajeshkumarsah** [comment] 2020-02-05 17:34
change src/style.css to src/style.scss is going to work. This things you are not going to achieve through console do again ng serve you will get probelm.

**Comment by AbdulrahmanMasoud** [comment] 2020-04-01 09:51
طبعا هتلاقي واحد عربي دلوقت مش عارف المشكله فيه 
ف احب  اعرفك ان المشكله هي ان انت ضايف item
واحد بس 
ف انت ضيف كمان item
او كذا item 
وهي هتظهر معاك

**Comment by AbdulrahmanMasoud** [comment] 2020-04-01 09:54
You must add more than one item
to show the nav and dots

**Comment by jnt2811** [comment] 2020-08-12 06:09
the number of items you want to add has to be bigger than the number of items you want to display

**Comment by Gomathiss** [comment] 2020-11-11 16:32
> I happens when `items:` is equal to current slide blocks count. For example you have 4 image in slider and `items` set to 4. It will add `disabled:` manually. Adding images to slider more than count of `items:` will fix problem.

Great

**Comment by Gomathiss** [comment] 2020-11-18 08:43
Hi please tell answer anyone i want to use 2 row carousel totally more than 30 items, i want to see 2 rows 5  items each row(1st row 5 items, 2nd row 5 items) totally 10 items visible.......please help anyone

**Comment by alim-14** [comment] 2020-11-21 12:28
> Hi please tell answer anyone i want to use 2 row carousel totally more than 30 items, i want to see 2 rows 5 items each row(1st row 5 items, 2nd row 5 items) totally 10 items visible.......please help anyone

https://codepen.io/Tolc/pen/OJXyKpo

**Comment by entryword** [comment] 2021-01-12 07:17
> just display **_owl-nav_** as block and give it important
> `.owl-nav { display: block !important; }`

This saved my day! Thank you!!

**Comment by iAmWaris97** [comment] 2021-03-31 12:34
I had the same problem and solved it by CSS display property as bellow:
first, inspect your document while it still shows the nav icons, and find the class name of the nav icons and then write the CSS as below:

Working for me
.owl-carousel .owl-nav.disabled{
    display: block;
}

**Comment by mghoreishi** [comment] 2021-05-06 07:46
I am getting the same issue.
Working for me


 **$('.owl-carousel').owlCarousel({
            loop: true,
            margin: 10,
            autoplay: true,
            autoplayTimeout: 3000,
            autoplayHoverPause: true,
            margin: 10,
            navText: ["<div class='nav-btn prev-slide'></div>", "<div class='nav-btn next-slide'></div>"],
            responsive: {
                0: {
                    items: 1
                },
                600: {
                    items: 2
                },
                1000: {
                    items: 3
                }
            }
        });
        $('.owl-carousel').trigger('play.owl.autoplay', [3000])**

**Comment by Neomedes** [comment] 2021-06-01 07:04
I am getting the same issue. Please reopen and fix for the case of "center: true", because only half the existing elements are shown initially. Having "items: 7" and 6 items in carousel means only 3-4 are displayed. Please remove the necessity to always use a workaround.

**Comment by thabit9** [comment] 2021-06-19 08:13
> hay the problem is if you make a items:3 for ex to view 3 element/slide and you put 3 items only so the nav will be disabled try to put more than 3 element so nav will work because now you have more than 3 element and you configure to present 3 items only/ slide so you should use nav to see more elements. make sense

The problem was i had mentioned 3 items to view in my js and i also had 3 items on my row.
$('.carousel-testimony').owlCarousel({
			center: true,
			loop: true,
			items:1,
			margin: 30,
			stagePadding: 0,
			nav: true,
			navText: ['<span class="ion-ios-arrow-back">', '<span class="ion-ios-arrow-forward">'],
			responsive:{
				0:{
					items: 1
				},
				600:{
					items: 2
				},
				1000:{
					items: 3
				}
			}
		});
	};
	carousel();

in your html row put atleast 4 items

**Comment by parisaaxp** [comment] 2021-08-25 11:41
`<div class="owl-nav" disabled> buttons and stuffs </div>`
`<div class="owl-dots" disabled> empty </div>`

**problem uno :**
owl-dots is empty .... where does it gets its elements?

**problem dos :**
both are disabled even when I set the options TRUE ...

my items are set to 1 and I have 3 three AutoPlay looping sliders on my page... 
**HELP ... T_T**

**Comment by qasim-dzinemedia** [comment] 2022-12-21 07:53
I had the same issue, first I removed the display none class from the owl CSS which worked for me but later I realized this is not an issue of CSS  just add more than one item in the carousel and set the value of dots and nav "true" it will work

**Comment by raufp6** [comment] 2023-03-14 05:54
I had same issue, please check your items count in script. if items count is 4 you must add more than 4 item div in carousel .

**Comment by adamyates91** [comment] 2023-06-28 11:17
I resolved the issue by adding a CSS selector in the div above, then using display: inherit; by targeting owl-nav.

Example below:

```
<style>
.specific-carousel .owl-dots.disabled, .owl-cursor-hover .owl-carousel .owl-nav.disabled {
  display: inherit!important;
}
</style>

<section class="section specific-carousel">
  <div class="container">
    <div class="owl-carousel owl-nav-overlay" data-owl-nav="true" data-owl-dots="false" data-owl-loop="true" data-owl-items="3" data-owl-xs="2" data-owl-sm="2" data-owl-margin="20" owl-lazy="true">
      <item>
      </item>
    </div>
  </div>
</section>
```

**Comment by manojsharmadkd** [comment] 2023-07-19 06:54
[](url)

**Comment by cgdmohamed** [comment] 2023-07-31 20:55
> طبعا هتلاقي واحد عربي دلوقت مش عارف المشكله فيه ف احب اعرفك ان المشكله هي ان انت ضايف item واحد بس ف انت ضيف كمان item او كذا item وهي هتظهر معاك

ياخي انت دماغ 😂
