### ISSUE TITLE
Owl Carousel 2.1 and jquery 3 error

### ISSUE THREAD

**Issue by e-retailer** [OwlCarousel2/OwlCarousel2#1509] opened 2016-07-28 07:45 UTC
Hello after upgrading owl carousel and jquery i get the following error:
`Uncaught TypeError: $(...).find(...).andSelf is not a function`

How do i fix this?

**Comment by volodymyrlut** [comment] 2016-08-03 11:01
Same issue.
The reason is that `andSelf` method is deprecated in jQuery 1.8. `andSelf` now is an alias for `addBack`, which should be used with jQuery 1.8 and later, so you can just replace it.
@e-retailer and everybody, to fix this right now, you can rollback your jQuery to 1.7. 
I'll try to make plugin compatible with latest version of jQuery this evening.

**Comment by mpash** [comment] 2016-09-18 01:06
It's been well over a month since you said this would be fixed.

**Comment by volodymyrlut** [comment] 2016-09-18 01:11
@mpash @e-retailer 
Sorry, guys, completely forgot about it, I'll open PR with fixed code tomorrow.
Thank you for the reminder.

As a workaround for now (and actually this was the one I'll use in PR) you can find and replace andSelf to addBack through the source code of owl-carousel.

**Comment by volodymyrlut** [comment] 2016-09-18 01:17
@mpash @e-retailer 
Well, looks like my job is done:

It's fixed in #1442 

This issue should be closed for now, because the problem is solved and even merged, so here is [the release](https://github.com/OwlCarousel2/OwlCarousel2/releases/tag/2.1.6) with this solution by @nebrot.

**Comment by mpash** [comment] 2016-09-18 01:21
It's full blown abandonware. I appreciate you taking the time to look into the issues, but David (@daviddeutsch) has apparently taken some mental health break for several months now and there has been no movement on the package.

**Comment by ttkien175** [comment] 2016-10-14 08:25
Please update to be compatible with the latest jQuery, I tried to addBack instead andSelf and it runs very well. Thank you very much! #ttkien175

**Comment by daviddeutsch** [comment] 2016-10-25 21:21
Fixed in 2.2.0. :confetti_ball:

**Closed by daviddeutsch** 2016-10-25 21:21 UTC

**Comment by kientran175** [comment] 2016-10-26 01:23
@daviddeutsch  
Great! Thank you so much!

**Comment by gseilheimer** [comment] 2016-10-30 22:36
Sorry, but I got the same error with jQuery 3.1.1 and owlCarousel 2.2.

**ERROR**
File: jquery-3.1.1.min.js
Row: 31643
Error: TypeError: b.find("[data-merge]").andSelf is not a function. (In 'b.find("[data-merge]").andSelf("[data-merge]")', 'b.find("[data-merge]").andSelf' is undefined)

**Comment by wyz1** [comment] 2016-11-17 21:55
Did not work for me. I had to ref my hosted copy if jquery 1.11.1 and changed the andSelf to addBack,. I however don't have the benefit on CDN hosted Jquery.

**Comment by vishalsankpal** [comment] 2019-11-05 07:58
The owl carousel is not compatible with the latest jquery. It is depended on jquery version 2.
