### ISSUE TITLE
1 px height image

### ISSUE THREAD

**Issue by laminr** [OwlCarousel2/OwlCarousel2#2039] opened 2017-08-29 15:43 UTC
Goodday,

On the homepage of my website, where I have put the carrousel, the carousel start almost every time with the first picture with a **height** of **1px**, then while sliding to the second, it takes the normal size.

check on: www.vytashop.com

please help

**Comment by saturdaynight** [comment] 2017-09-08 09:32
I have the same problem. Did you find a solution?

**Comment by laminr** [comment] 2017-09-08 09:33
unfortunately not :'-(

**Comment by saturdaynight** [comment] 2017-09-08 09:43
Try this, might need to adjust the value. It worked for me.

.owl-height {min-height: 500px;    height:auto !important;    height: 500px; }

**Comment by laminr** [comment] 2017-09-08 09:47
Will have another try with that, thanks
I think my issue with it was that the carousel is not more responsive in height then....

**Comment by saturdaynight** [comment] 2017-09-08 09:56
my issue only happen when i press CTRL+F5 or first time image loads.

**Comment by laminr** [comment] 2017-09-08 10:52
me too, the first load of the page...

**Comment by piotrorlowski-idego** [comment] 2017-10-12 09:42
The same issue here ... setting min-height however will remove rwd concept

**Comment by robertrhu** [comment] 2018-01-15 20:17
Anyone able to find a good fix for this? I'm completely stuck.

Started this thread here...
https://github.com/OwlCarousel2/OwlCarousel2/issues/2185

**Comment by pascalporedda** [comment] 2018-02-24 14:32
Duplicate of #556 

Has been fixed with the latest commit and will be released soon.

**Closed by pascalporedda** 2018-02-24 14:32 UTC
