### ISSUE TITLE
PLEASE HELP!! On initial load, height is messed up.

### ISSUE THREAD

**Issue by saturdaynight** [OwlCarousel2/OwlCarousel2#2054] opened 2017-09-08 09:31 UTC
Hi all, sorry to seem to urgent but it is!!

When the slider initially loads the height is messed up and you cannot see the slider.

To see this I do CTRL+F5 on Chrome.

I hope someone can help.

Thanks

**Comment by saturdaynight** [comment] 2017-09-08 09:36
I see in the owl-height, it is incorrectly set:

<div class="owl-stage-outer owl-height" style="height: 53px;">

It should be 630px!

Could it be because the image hasn't been loaded by the time the height is set?

How can I fix this?

**Comment by saturdaynight** [comment] 2017-09-08 09:43
I think I fixed it.

Add this to your CSS it worked for me, might need to adjust the value.

.owl-height {min-height: 500px;    height:auto !important;    height: 500px; }

**Comment by keefyhub** [comment] 2017-09-08 10:38
if you havent already, I usually set my carousel to initialise after window load. If the image has no loaded and that is setting the height, it can cause issues

**Comment by saturdaynight** [comment] 2017-09-08 11:08
Hi Keefy, how do i do this?

**Comment by saturdaynight** [comment] 2017-09-08 11:09
this is my code:

<script>
jQuery(document).ready(function($) {	
$(document).ready(function(){
  $(".owl-carousel").owlCarousel({
  nav : true,
      autoPlay : false,
      autoHeight: true,
	  items: 1,
	  dots: false,
	  navText : ["",""]
	  });
});
	});
</script>

**Comment by saturdaynight** [comment] 2017-09-08 11:09
`<script>
jQuery(document).ready(function($) {	
$(document).ready(function(){
  $(".owl-carousel").owlCarousel({
  nav : true,
      autoPlay : false,
      autoHeight: true,
	  items: 1,
	  dots: false,
	  navText : ["",""]
	  });
});
	});
</script>`

**Comment by keefyhub** [comment] 2017-09-08 11:44
change `jQuery(document).ready(` to `jQuery(window).load(`

Might not help but worth a try

**Comment by saturdaynight** [comment] 2017-09-08 13:02
thanks that did work but delayed rendering of the page whereas the method I used above 'seems' to solve the problem without affecting load time.

Thanks

**Comment by keefyhub** [comment] 2017-09-08 14:02
Only issue with setting a height is when you are working responsively, you might get some white space where the height of the carousel does not equal the height of the images.

**Comment by 55N-12E** [comment] 2017-09-12 03:09
Hello i thing we meet the same problem and i see all of you answer  and i notice the problem is on the height  and i try to write a css in .owl-carousel:{height:auto;}  it seem's like fix the problem
i'm still testing
by the way i'm a Chinese coder so my English maybe bad and i'm learning right now  hope i help you XD

**Comment by pascalporedda** [comment] 2018-02-24 14:33
Duplicate of #556 

This issue will be solved with the next release.

**Closed by pascalporedda** 2018-02-24 14:33 UTC

**Comment by haow-abc** [comment] 2019-02-27 19:20
`dots: false` can solve the height issue if you don't need dots and don't want extra height for your carousel
